#!/bin/bash

#############################################################################
## A tighter, bashrc. Less floof, more oumph.                              ##
## The plan is to make this my default everywhere.                         ##
##                                                                         ##
## And when I'm done, there'll be a wget -O- installer too.                ##
#############################################################################

####################
## .bashrc basics ##
####################

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# If this is an xterm set the title to host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

####################
## History lesson ##
####################

# Search through history with arrow keys
bind '"\e[A": history-search-backward' 2>/dev/null
bind '"\e[B": history-search-forward' 2>/dev/null

# Don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

######################
## All things Shopt ##
######################

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# Some autocorrect for cd
shopt -s cdspell

##########################################
## Colours, powerline, such shenanigans ##
##########################################

# Just a basic prompt
export PS1='\[\e[1;38;5;244m\]\t \[\e[1;36m\]\u@\H \[\e[1;33m\]\w \[\e[1;36m\]\$ \[\e[0m\]'

# Powerline
function _update_ps1() {
    PS1=$(powerline-shell $?)
}

if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

########
## ls ##
########

if which eza >/dev/null; then
    alias ls="eza"
    alias ll="eza -l"
    alias la="eza -la"
    alias lt=" eza -l --tree"
else
    alias ls="ls --color=always"
    alias ll="ls -l"
    alias la="ls -lA"
fi

for alias in lsl sls lsls sl l s; do alias $alias=ls; done

###################
## Root warning! ##
###################

if [ `id -u` -eq 0 ]; then
    start="\033[1;37;41m"
    end="\033[0m"
    printf "\n"
    printf "  $start                                                                    $end\n"
    printf "  $start  WARNING: You are in a root shell. This might be a very bad idea.  $end\n"
    printf "  $start                                                                    $end\n"
    printf "\n"
fi

#########################
## Path & Applications ##
#########################

# Setup ~/.local/bin
export PATH="$PATH:$HOME/.local/bin"

# Setup GOPATH
export GOPATH="$PATH:/usr/local/go"
export PATH="$GOPATH/bin:$PATH"

#####################
## Online services ##
#####################

# Termbin
alias tb="nc termbin.com 9999"

# setup qbin and transfer.sh and get back to this
# txt.loidor.com && file.loidor.com

####################
## Other thingies ##
####################

# If ag isn't installed, set grep to -rn. Also, force grep color
alias grep="grep --color=always"
which ag >/dev/null || alias ag="grep -rn"

# Ubuntu effs up fd and calls it fdfind. Now it's fd again.
! which fdfind >/dev/null || alias fd=fdfind

#############
## Aliases ##
#############

alias nano="micro"
alias rm="rm -r"
alias update="sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean"
alias ..="cd .."
alias ...="cd ..; cd .."
alias ....="cd ..; cd ..; cd .."
alias o="xdg-open"
alias c="clear"
alias spotdl="spotdl --preload"
alias tmuxa="tmux attach"

# Some error handling
alias mc="mv"
alias cf="cd"
alias apt="sudo apt"
alias reboot="sudo reboot"
alias poweroff="sudo poweroff"
alias systemctl="sudo systemctl"

################################
## Homestretch - custom stuff ##
################################

eval "$(thefuck --alias)"
